# Exact copy from working sample with Flutter integration
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/tuya/tuya-pod-specs.git'

platform :ios, '13.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  
  # Core Tuya SDK
  pod 'ThingSmartCryption', :path => './ios_core_sdk'
  pod 'ThingSmartHomeKit', '~> 6.7.0'
  pod 'ThingSmartBusinessExtensionKit', '~> 6.7.0'
  pod 'ThingSmartBusinessExtensionKitBLEExtra','~> 6.7.0'
  
  # Core BizBundles (for device pairing and control)
  pod 'ThingSmartActivatorBizBundle'
  pod 'ThingSmartPanelBizBundle'
  pod 'ThingSmartSceneBizBundle', '~> 6.7.0'
  
  # IPC/Camera SDKs and BizBundles (for camera/video surveillance devices)
  pod 'ThingSmartCameraKit'
  pod 'ThingSmartCameraM'
  pod 'ThingSmartIPCKitBizBundle'
  pod 'ThingSmartCameraPanelBizBundle'
  pod 'ThingSmartCameraRNPanelBizBundle'
  
  # Scene BizBundles (for smart scene automation)
  pod 'ThingSmartSceneExtendBizBundle'
  pod 'ThingSmartMiniAppBizBundle'
  pod 'ThingSmartMapKitBizBundle'
  
  # Smart Lock SDK (for locks with video/camera features)
  # Note: Lock panels use ThingSmartPanelBizBundle + Camera SDKs above
  pod 'ThingSmartLockKit', '~> 6.7.0'
  
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  # From working sample
  `cd Runner; [[ -f AppKey.swift ]] || cp ../ios_backup_old/Runner/AppKey.swift AppKey.swift;`
  
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    target.build_configurations.each do |config|
      config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "13.0"
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      # Tuya SDK only supports x86_64 simulators (Rosetta), not arm64
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
  end
  
  # Also configure the Runner target
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end
  end
end
