source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/TuyaInc/TuyaPublicSpecs.git'

source 'https://github.com/tuya/tuya-pod-specs.git'

platform :ios, '15.6'
project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

 target 'Runner' do
 use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
      pod "ThingSmartBusinessExtensionKit",'~> 6.7.0'

  pod 'ThingSmartSweeperKit','~> 6.7.0'
  pod 'ThingSmartDeviceDetailBizBundle','~> 6.7.0'
  pod 'ThingSmartSkillQuickBindBizBundle','~> 6.7.0'
  pod 'ThingSmartHelpCenterBizBundle','~> 6.7.0'
  pod 'ThingSmartActivatorBizBundle','~> 6.7.0'
  pod 'ThingSmartMessageBizBundle','~> 6.7.0'
  pod 'ThingSmartSceneBizBundle','~> 6.7.0'
  pod 'ThingSmartMallBizBundle','~> 6.7.0'
  pod 'ThingAdvancedFunctionsBizBundle','~> 6.7.0'
  pod 'ThingSmartMarketingBizBundle','~> 6.7.0'
  pod 'ThingSmartGroupHandleBizBundle','~> 6.7.0'
  pod 'ThingSmartOutdoorKit','~> 6.7.0'
  pod 'ThingSmartDeviceSyncBizBundle','~> 6.7.0'
  pod 'ThingSmartShareBizBundle','~> 6.7.0'
  pod 'ThingSmartCameraRNPanelBizBundle','~> 6.7.0'
  pod 'ThingSmartLockKit','~> 6.7.0'
  pod 'ThingSmartCameraPanelBizBundle','~> 6.7.0'
  pod 'ThingSmartCameraKit','~> 6.7.0'
  pod 'ThingSmartLangsExtraBizBundle','~> 6.7.0'
  pod 'ThingSmartFamilyBizBundle','~> 6.7.0'
  pod 'ThingSmartBusinessExtensionKit','~> 6.7.0'
  pod 'ThingSmartOTABizBundle','~> 6.7.0'
  pod 'ThingSmartCameraSettingBizBundle','~> 6.7.0'
  pod 'ThingSmartCloudServiceBizBundle','~> 6.7.0'
  pod 'ThingSmartActivatorExtraBizBundle','~> 6.7.0'
  pod 'ThingSmartThemeManagerBizBundle','~> 6.7.0'

  pod 'ThingSmartPanelBizBundle','~> 6.7.0' # open cv here
   pod 'ThingSmartCryption', :path => './ios_core_sdk'


end

# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     flutter_additional_ios_build_settings(target)
#
#     target.build_configurations.each do |config|
#       # Fix for architecture issues
#       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
#
#       # For Apple Silicon Macs
#       if config.name == 'Debug'
#         config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
#       end
#
#       # Architecture settings
#       config.build_settings['ARCHS'] = 'arm64'
#
#       # Exclude arm64 for simulator if on Intel Mac (uncomment if needed)
#       # config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
#     end
#   end
# end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
