/// Flutter icons NavIcons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NavIcons
///      fonts:
///       - asset: fonts/NavIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class NavIcons {
  NavIcons._();

  static const _kFontFam = 'NavIcons';
  static const String? _kFontPkg = null;

  static const IconData setting_3_svgrepo_com = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorite_svgrepo_com = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_wifi_angle_svgrepo_com_2 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
